name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import project
        run: godot --headless --editor --quit
      - name: Build APK
        run: mkdir -p build && godot --headless --path . --export-debug "Android" build/Arcana-Realms-Prototype-01.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Arcana-Realms-Prototype-01-APK
          path: build/Arcana-Realms-Prototype-01.apk
