name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  GODOT_VERSION: 4.7.1

jobs:
  build-apk:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -p "$HOME/.local/share/godot/export_templates"
          mkdir -p "$HOME/.config"
          mkdir -p build
          rm -rf "$HOME/.config/godot"
          cp -a /root/.config/godot "$HOME/.config/godot"
          rm -rf "$HOME/.local/share/godot/export_templates/4.7.1.stable"
          cp -a /root/.local/share/godot/export_templates/4.7.1.stable "$HOME/.local/share/godot/export_templates/4.7.1.stable"
          ls "$HOME/.local/share/godot/export_templates/4.7.1.stable" | grep android
          cat "$HOME/.config/godot/editor_settings-4.7.tres"

      - name: Import
        run: godot --headless --import --quit || true

      - name: Export
        run: godot --headless --verbose --export-debug "Android" build/Arcana-Realms-Prototype-02.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Arcana-Realms-Prototype-02-APK
          path: build/Arcana-Realms-Prototype-02.apk
          if-no-files-found: error
